# Lab 02 - NumPy Exercises 



#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones
np.ones(10)


#### Create an array of 10 fives

In [13]:
list1 =[5]*10
np.array(list1)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

np.arange(10,51)


#### Create an array of all the even integers from 10 to 50

In [24]:
np.arange(10,51,2) 

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [26]:
import numpy as np
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [30]:
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [34]:
import numpy as np

random_number = np.random.rand()

print(random_number)

0.258563908440414


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [36]:
import numpy as np
random_array = np.random.randn(25)

print(random_array)

[-0.74896226 -1.40433052 -0.39658264 -0.43425025 -2.89334956  1.41451299
 -0.20530592 -1.12396311  0.93791192 -0.52196375 -1.16991805  0.91836581
 -0.43695509  0.49549251  0.39151812 -0.38167394  0.99897443 -0.29262083
  1.19815496  0.47484363  0.35172855  0.87726406  1.1428804   0.00381457
 -0.08077222]


#### Create the following matrix:

In [38]:
import numpy as np

matrix = np.arange(0.01, 1.01, 0.01).reshape(10, 10)

print(matrix)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [40]:
import numpy as np


linear_array = np.linspace(0, 1, 20)

print(linear_array)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [42]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
import numpy as np

mat = np.arange(1, 26).reshape(5, 5)

print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [44]:
result = mat[2:, 1:]

print(result)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [46]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE


20


In [48]:
result = mat[3, 4] 

print(result)

20


In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [84]:
import numpy as np

mat = np.arange(1, 26).reshape(5, 5)

result = mat[1:4, 1:2]

print(result)

[[ 7]
 [12]
 [17]]


In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [62]:
import numpy as np


mat = np.arange(1, 26).reshape(5, 5)


result = mat[4, :]


print(result)

[21 22 23 24 25]


In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [64]:
import numpy as np

mat = np.arange(1, 26).reshape(5, 5)

result = mat[3:, :]

print(result)


[[16 17 18 19 20]
 [21 22 23 24 25]]


### Now do the following

#### Get the sum of all the values in mat

In [66]:
import numpy as np
mat = np.arange(1, 26).reshape(5, 5)

total_sum = np.sum(mat)

print(total_sum)

325


#### Get the standard deviation of the values in mat

In [86]:
import numpy as np

mat = np.arange(1, 26).reshape(5, 5)

std_deviation = np.std(mat)

print(std_deviation)

7.211102550927978


# Great Job!